export const USER_LOGIN = "USER_LOGIN"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE"

export const CHECK_SESSION = "CHECK_SESSION"
export const CHECK_SESSION_SUCCESS = "CHECK_SESSION_SUCCESS"
export const CHECK_SESSION_FAILURE = "CHECK_SESSION_FAILURE"

export const CLEAR_SESSION = "CLEAR_SESSION"